---
title: "MATH 392 Problem Set 2"
output: 
  github_document:
    fig_height: 3
    fig_width: 6
---


```{r, include=FALSE}
require(tidyverse) # load package
require(resampledata)
options(digits=4) # print 4 decimal places only
set.seed(1999) # set seed for reproducibility
```

### Exercises 3.4, 3.16, 3.22

### Exercise 3.31

Just as $T(X)$ is a random variable, so too is its corresponding p-value, $p = P(T(X) \ge t)$. What is the distribution of a p-value when the null hypothesis is true? Provide two approaches: analytical and simulation. For the simulation approach, you can either consider a permutation test or an asymptotic approximation that you might be familiar with (Normal, $t$, $\chi^2$, etc). In either event, it will be easier if you define a continuous population distribution rather than a discrete one.


### Exercise 3.32

Define $X = Z^2$, where $Z$ follows the standard normal distribution. Show that $X \sim {\chi^2}_{\textrm{df} = 1}$.


### Challenge question

Explore the convergence properties of the $\chi^2$ statistics to the $\chi^2$ distribution when we model an individual cell count as Poisson. This exploration can take the form of analytic and/or simulation approaches.


### Notes

- Answering ex. 3.22 does not require transcribing that data set into R, thanks
goodness.
- Ex. 3.31 and 3.32 feature canonical results in mathematical staitstics, which is to say: they are eminently googleable. I encourage you to avoid googling here; turn it over in your head awhile, struggle with it, and when you get frustrated, ask questions over slack.
